### ISSUE TITLE
UIAction icons suggestion

### ISSUE THREAD

**Issue by 8ofproject** [alextrob/ARChromeActivity#15]
May I suggest a little changes, please? :+1: 

It would be nice if action icon on iOS 7 has the same appearance as other action icons. :cool: 

Example: now/suggestion

![ios7-now-maybe](https://cloud.githubusercontent.com/assets/6408861/7452782/bcd96822-f26a-11e4-909f-12b2d589f069.png)

Also, there is a little problem on iPad 2 (iOS 8.3) - only real iPad, not the Simulator - not sure why but chrome UIAction image is just too big. Looks like other iPads show the icon well.

![ios8-ipad-now](https://cloud.githubusercontent.com/assets/6408861/7452789/ce8ff914-f26a-11e4-9068-1517f5c71783.png)

**Comment by 8ofproject** [comment]
Created pull request with fix for all of the problems:
https://github.com/alextrob/ARChromeActivity/pull/16

Please, disregard russian title in chrome UIAction - it's set via setTitle method. :cookie:

**Comment by 8of** [comment]
Looks like iOS 7 is too old now. The issue isn't relevant no more.
