### ISSUE TITLE
Not showing icon when using CocoaPods

### ISSUE THREAD

**Issue by dfmuir** [alextrob/ARChromeActivity#21]
I am using CocoaPods and iOS 9 and just see a blank icon in the activity sheet.

**Comment by anscho** [comment]
Hey @dfmuir, I opened a pull request related to this: https://github.com/alextrob/ARChromeActivity/pull/23

It would be great to know if that solution works for you as well.

**Comment by alextrob** [comment]
Fixed in version 1.0.6, now available in Cocoapods.
